# WELCOME MESSAGE
welcome: Benvenuto nel pannello di amministrazione di

# VOCABOLARY
vocabolary:
  dashboard: Dashboard
  users: Utenti
  name: Nome
  username: Username
  email: Email
  permission: Permessi
  password: Password
  password_confirmation: Conferma password
  edit: Modifica utente
  new: Nuovo utente
  save: Salva

# FORMS
forms:
  base_informations: Informazioni base
  user_password: Password dell'utente
  password_edit_settings: Lasciare il campo vuoto per non modificare la password

# SUPERUSERS
superusers:
  not_found: L'utente cercato non esiste
  success_create: L'utente è stato creato con successo
  failed_create: L'utente non è stato creato poichè alcuni dati non sono stati inseriti o non sono corretti
  permission_create: Non puoi creare un utente con permessi superiori ai tuoi
  success_update: L'utente è stato modificato correttamente
  failed_update: L'utente non è stato modificato poichè alcuni dati non sono stati inseriti o non sono corretti
  permission_update: Non puoi modificare un utente con permessi superiori o uguali ai tuoi
  level_update: Non puoi aumentarti il livello da solo. Per farlo devi chiedere ad un utente con permessi maggiori
  admin_update: L'utente amministratore non può essere modificato da nessuno
  success_destroy: L'utente è stato eliminato correttamente
  failed_destroy: L'utente non è stato eliminato a causa di un errore
  itself_destroy: Non puoi eliminare te stesso
  permission_destroy: Non puoi eliminare un utente con permessi superiori o uguali ai tuoi
