input:
  required: Campo obbligatorio
  choose_file: Seleziona file
  selected_files: Files selezionati

index:
  actions: Azioni
  show: Visualizza
  edit: Modifica
  delete: Elimina
  search: Cerca

form_validation:
  number: Il valore deve essere un numero.
  required: Campo obbligatorio.
  email: Inserisci un indirizzo email valido.
  char : Numero errato di caratteri.
  pass_same: I campi devono avere lo stesso valore.
  check: Non puoi lasciare vuoto questo campo.
